//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_sync_web {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("task_sync_web.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0001 {
            get {
                return ResourceManager.GetString("EW0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0002 {
            get {
                return ResourceManager.GetString("EW0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{2}～{1}文字の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0003 {
            get {
                return ResourceManager.GetString("EW0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}～{2}の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0004 {
            get {
                return ResourceManager.GetString("EW0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の日付形式が正しくありません。yyyy/MM/ddで入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0005 {
            get {
                return ResourceManager.GetString("EW0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始日は終了日より前でなければいけません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0006 {
            get {
                return ResourceManager.GetString("EW0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間の形式が正しくありません。hh:mmで入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0007 {
            get {
                return ResourceManager.GetString("EW0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間の形式が正しくありません。hh:mm:ssで入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0008 {
            get {
                return ResourceManager.GetString("EW0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角数字のみ使用できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0009 {
            get {
                return ResourceManager.GetString("EW0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数字のみ使用できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0010 {
            get {
                return ResourceManager.GetString("EW0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数字記号のみ使用できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0011 {
            get {
                return ResourceManager.GetString("EW0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0101 {
            get {
                return ResourceManager.GetString("EW0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に一致するデータが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0102 {
            get {
                return ResourceManager.GetString("EW0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0500 {
            get {
                return ResourceManager.GetString("EW0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0501 {
            get {
                return ResourceManager.GetString("EW0501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW0502 {
            get {
                return ResourceManager.GetString("EW0502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインIDまたはパスワードが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1001 {
            get {
                return ResourceManager.GetString("EW1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社情報の取得に失敗しました。システム管理者に問い合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1002 {
            get {
                return ResourceManager.GetString("EW1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン更新処理に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1003 {
            get {
                return ResourceManager.GetString("EW1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1004 {
            get {
                return ResourceManager.GetString("EW1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この管理者ログインIDは利用開始日前です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1005 {
            get {
                return ResourceManager.GetString("EW1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この管理者ログインIDは利用終了日を過ぎています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1006 {
            get {
                return ResourceManager.GetString("EW1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   異なるログインがあったため自動ログアウトされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1010 {
            get {
                return ResourceManager.GetString("EW1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のパスワードが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1101 {
            get {
                return ResourceManager.GetString("EW1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいパスワードと新しいパスワード(確認用)が一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1102 {
            get {
                return ResourceManager.GetString("EW1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のパスワードと新しいパスワードが同じです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1103 {
            get {
                return ResourceManager.GetString("EW1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者情報の取得に失敗しました。システム管理者に問い合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1104 {
            get {
                return ResourceManager.GetString("EW1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいパスワードは半角数字、半角英小文字、半角英大文字、半角記号のうち2種以上の組合せである必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1105 {
            get {
                return ResourceManager.GetString("EW1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録修正フラグは1か2で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1201 {
            get {
                return ResourceManager.GetString("EW1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの拡張子がサポート対象外です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1202 {
            get {
                return ResourceManager.GetString("EW1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込対象のファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1203 {
            get {
                return ResourceManager.GetString("EW1203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が既に存在するため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1204 {
            get {
                return ResourceManager.GetString("EW1204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が存在しないため修正できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1205 {
            get {
                return ResourceManager.GetString("EW1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用停止フラグは0か1で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1206 {
            get {
                return ResourceManager.GetString("EW1206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録・修正の対象のデータが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1207 {
            get {
                return ResourceManager.GetString("EW1207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が重複しているため修正できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1208 {
            get {
                return ResourceManager.GetString("EW1208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が重複しているため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1209 {
            get {
                return ResourceManager.GetString("EW1209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   修正リストと登録リストは{0}重複できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1210 {
            get {
                return ResourceManager.GetString("EW1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録対象行の{0}は空白でなければいけません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1211 {
            get {
                return ResourceManager.GetString("EW1211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列名が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1212 {
            get {
                return ResourceManager.GetString("EW1212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業日付(始)を日付形式に変更できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1300 {
            get {
                return ResourceManager.GetString("EW1300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業日付(終)を日付形式に変更できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1301 {
            get {
                return ResourceManager.GetString("EW1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の形式が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1302 {
            get {
                return ResourceManager.GetString("EW1302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の形式が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1303 {
            get {
                return ResourceManager.GetString("EW1303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業項目が存在しません。再選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1304 {
            get {
                return ResourceManager.GetString("EW1304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業終了時刻は、作業開始時刻以上でなければいけません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1305 {
            get {
                return ResourceManager.GetString("EW1305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中断時間は0以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1306 {
            get {
                return ResourceManager.GetString("EW1306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中断時間が作業時間を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW1307 {
            get {
                return ResourceManager.GetString("EW1307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EW9000 {
            get {
                return ResourceManager.GetString("EW9000", resourceCulture);
            }
        }
    }
}
