//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_sync_web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("task_sync_web.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は必須です。.
        /// </summary>
        public static string EW0001 {
            get {
                return ResourceManager.GetString("EW0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}文字以内で入力してください。.
        /// </summary>
        public static string EW0002 {
            get {
                return ResourceManager.GetString("EW0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{2}～{1}文字の間で入力してください。.
        /// </summary>
        public static string EW0003 {
            get {
                return ResourceManager.GetString("EW0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}～{2}の間で入力してください。.
        /// </summary>
        public static string EW0004 {
            get {
                return ResourceManager.GetString("EW0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の日付形式が正しくありません。yyyy/MM/ddで入力してください。.
        /// </summary>
        public static string EW0005 {
            get {
                return ResourceManager.GetString("EW0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始日は終了日より前でなければいけません。.
        /// </summary>
        public static string EW0006 {
            get {
                return ResourceManager.GetString("EW0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間の形式が正しくありません。hh:mmで入力してください。.
        /// </summary>
        public static string EW0007 {
            get {
                return ResourceManager.GetString("EW0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間の形式が正しくありません。hh:mm:ssで入力してください。.
        /// </summary>
        public static string EW0008 {
            get {
                return ResourceManager.GetString("EW0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は半角数字のみ使用できます。.
        /// </summary>
        public static string EW0009 {
            get {
                return ResourceManager.GetString("EW0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は半角英数字のみ使用できます。.
        /// </summary>
        public static string EW0010 {
            get {
                return ResourceManager.GetString("EW0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象データが存在しません。.
        /// </summary>
        public static string EW0101 {
            get {
                return ResourceManager.GetString("EW0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索条件に一致するデータが存在しません。.
        /// </summary>
        public static string EW0102 {
            get {
                return ResourceManager.GetString("EW0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ取得に失敗しました。.
        /// </summary>
        public static string EW0500 {
            get {
                return ResourceManager.GetString("EW0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録に失敗しました。.
        /// </summary>
        public static string EW0501 {
            get {
                return ResourceManager.GetString("EW0501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新に失敗しました。.
        /// </summary>
        public static string EW0502 {
            get {
                return ResourceManager.GetString("EW0502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインIDまたはパスワードが違います。.
        /// </summary>
        public static string EW1001 {
            get {
                return ResourceManager.GetString("EW1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会社情報の取得に失敗しました。システム管理者に問い合わせてください。.
        /// </summary>
        public static string EW1002 {
            get {
                return ResourceManager.GetString("EW1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン更新処理に失敗しました。.
        /// </summary>
        public static string EW1003 {
            get {
                return ResourceManager.GetString("EW1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインに失敗しました。.
        /// </summary>
        public static string EW1004 {
            get {
                return ResourceManager.GetString("EW1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 異なるログインがあったため自動ログアウトされました。.
        /// </summary>
        public static string EW1010 {
            get {
                return ResourceManager.GetString("EW1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のパスワードが違います。.
        /// </summary>
        public static string EW1101 {
            get {
                return ResourceManager.GetString("EW1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワードと新しいパスワード(確認用)が一致しません。.
        /// </summary>
        public static string EW1102 {
            get {
                return ResourceManager.GetString("EW1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のパスワードと新しいパスワードが同じです。.
        /// </summary>
        public static string EW1103 {
            get {
                return ResourceManager.GetString("EW1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理者情報の取得に失敗しました。システム管理者に問い合わせてください。.
        /// </summary>
        public static string EW1104 {
            get {
                return ResourceManager.GetString("EW1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録修正フラグは1か2で入力してください。.
        /// </summary>
        public static string EW1201 {
            get {
                return ResourceManager.GetString("EW1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの拡張子がサポート対象外です。.
        /// </summary>
        public static string EW1202 {
            get {
                return ResourceManager.GetString("EW1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取込対象のファイルが存在しません。.
        /// </summary>
        public static string EW1203 {
            get {
                return ResourceManager.GetString("EW1203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が既に存在するため登録できません。.
        /// </summary>
        public static string EW1204 {
            get {
                return ResourceManager.GetString("EW1204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が存在しないため修正できません。.
        /// </summary>
        public static string EW1205 {
            get {
                return ResourceManager.GetString("EW1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 利用停止フラグは0か1で入力してください。.
        /// </summary>
        public static string EW1206 {
            get {
                return ResourceManager.GetString("EW1206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録・修正の対象のデータが存在しません。.
        /// </summary>
        public static string EW1207 {
            get {
                return ResourceManager.GetString("EW1207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修正リストは{0}重複できません。.
        /// </summary>
        public static string EW1208 {
            get {
                return ResourceManager.GetString("EW1208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録リストは{0}重複できません。.
        /// </summary>
        public static string EW1209 {
            get {
                return ResourceManager.GetString("EW1209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修正リストと登録リストは{0}重複できません。.
        /// </summary>
        public static string EW1210 {
            get {
                return ResourceManager.GetString("EW1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業日付(始)を日付形式に変更できません。.
        /// </summary>
        public static string EW1300 {
            get {
                return ResourceManager.GetString("EW1300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業日付(終)を日付形式に変更できません。.
        /// </summary>
        public static string EW1301 {
            get {
                return ResourceManager.GetString("EW1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の形式が正しくありません。.
        /// </summary>
        public static string EW1302 {
            get {
                return ResourceManager.GetString("EW1302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の形式が正しくありません。.
        /// </summary>
        public static string EW1303 {
            get {
                return ResourceManager.GetString("EW1303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業項目選択が正しくありません。再選択してください。.
        /// </summary>
        public static string EW1304 {
            get {
                return ResourceManager.GetString("EW1304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業終了時刻は、作業開始時刻以上でなければいけません。.
        /// </summary>
        public static string EW1305 {
            get {
                return ResourceManager.GetString("EW1305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中断時間は0以上で入力してください。.
        /// </summary>
        public static string EW1306 {
            get {
                return ResourceManager.GetString("EW1306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予期せぬエラーが発生しました。.
        /// </summary>
        public static string EW9000 {
            get {
                return ResourceManager.GetString("EW9000", resourceCulture);
            }
        }
    }
}
